import { toEthereumAddress } from '@streamr/utils'
import { verifyMessage } from 'ethers'
import { readFileSync } from 'fs'
import { join } from 'path'
import { createSignedRequestMessage } from '../../../../src/plugins/storage/SignedRequest'
import { targetToLine } from '../../../../src/plugins/storage/purgeEndpoint'

// Cross-client vectors generated by the Pombo web/Android clients. Locks the
// node's `stored` request message byte-for-byte to what the clients sign, so
// the two never drift. Skew and nonce-once are the verifier's job (tested
// elsewhere); here we only check message construction and signature recovery.
const doc = JSON.parse(readFileSync(join(__dirname, 'storage-stored-vectors.json'), 'utf8'))

describe('stored request vectors (parity with the clients)', () => {

    it.each(doc.vectors.map((vector: any) => [vector.name, vector]))('matches the client: %s', (_name: string, vector: any) => {
        const message = createSignedRequestMessage(
            'stored',
            vector.streamId,
            vector.partition,
            vector.body.issuedAt,
            vector.body.nonce,
            vector.body.targets.map(targetToLine)
        )
        expect(message).toBe(vector.message)
        expect(toEthereumAddress(verifyMessage(message, vector.body.signature))).toBe(toEthereumAddress(vector.body.user))
    })
})
